import { useEffect, useState } from 'react';
import { ChevronDown, ChevronUp, Plus, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { slugify } from '@/components/admin/ProductForm';

const input='border border-neutral-300 rounded-lg px-3 py-2.5 text-sm outline-none focus:border-[#FFC21C]';

export function CategoriesManager({ onChanged }:{onChanged:()=>void}) {
  const [rows,setRows]=useState<any[]>([]); const [name,setName]=useState('');
  const load=async()=>{const {data}=await supabase.from('ecom_collections').select('*').order('position').order('title');setRows(data||[])};
  useEffect(()=>{load()},[]);
  const add=async()=>{if(!name.trim())return;await supabase.from('ecom_collections').insert({title:name.trim(),handle:slugify(name),is_visible:true,position:rows.length});setName('');await load();onChanged()};
  const patch=async(id:string,p:any)=>{await supabase.from('ecom_collections').update(p).eq('id',id);await load();onChanged()};
  const move=async(i:number,d:number)=>{const j=i+d;if(j<0||j>=rows.length)return;await Promise.all([patch(rows[i].id,{position:j}),patch(rows[j].id,{position:i})])};
  return <div><div className="flex gap-2 mb-5"><input className={`${input} flex-1`} value={name} onChange={e=>setName(e.target.value)} placeholder="New category name"/><button onClick={add} className="bg-[#FFC21C] px-5 rounded-lg font-extrabold flex items-center gap-2"><Plus className="w-4 h-4"/> Add</button></div><div className="space-y-2">{rows.map((r,i)=><div key={r.id} className="bg-white border rounded-xl p-4 flex flex-wrap items-center gap-3"><input className={`${input} flex-1 min-w-40`} defaultValue={r.title} onBlur={e=>patch(r.id,{title:e.target.value,handle:slugify(e.target.value)})}/><label className="text-xs font-bold flex items-center gap-2"><input type="checkbox" checked={r.is_visible!==false} onChange={e=>patch(r.id,{is_visible:e.target.checked})}/> Active</label><button onClick={()=>move(i,-1)} aria-label="Move up"><ChevronUp className="w-4 h-4"/></button><button onClick={()=>move(i,1)} aria-label="Move down"><ChevronDown className="w-4 h-4"/></button></div>)}</div></div>;
}

export function FiltersManager() {
  const [rows,setRows]=useState<any[]>([]); const [name,setName]=useState(''); const [newOptions,setNewOptions]=useState<Record<string,string>>({});
  const load=async()=>{const {data}=await supabase.from('product_filters').select('*, options:product_filter_options(*)').order('sort_order');setRows((data||[]).map((r:any)=>({...r,options:(r.options||[]).sort((a:any,b:any)=>a.sort_order-b.sort_order)})))};
  useEffect(()=>{load()},[]);
  const addFilter=async()=>{if(!name.trim())return;await supabase.from('product_filters').insert({name:name.trim(),slug:slugify(name),sort_order:rows.length});setName('');load()};
  const updateFilter=async(id:string,p:any)=>{await supabase.from('product_filters').update(p).eq('id',id);load()};
  const addOption=async(filter:any)=>{const label=(newOptions[filter.id]||'').trim();if(!label)return;await supabase.from('product_filter_options').insert({filter_id:filter.id,label,value:slugify(label)||label.toLowerCase(),sort_order:filter.options.length});setNewOptions(s=>({...s,[filter.id]:''}));load()};
  const updateOption=async(id:string,p:any)=>{await supabase.from('product_filter_options').update(p).eq('id',id);load()};
  const removeFilter=async(id:string)=>{if(confirm('Delete this filter and all its assignments?')){await supabase.from('product_filters').delete().eq('id',id);load()}};
  const removeOption=async(id:string)=>{if(confirm('Remove this filter option?')){await supabase.from('product_filter_options').delete().eq('id',id);load()}};
  const reorder=async(list:any[],i:number,d:number,table:string)=>{const j=i+d;if(j<0||j>=list.length)return;await Promise.all([supabase.from(table).update({sort_order:j}).eq('id',list[i].id),supabase.from(table).update({sort_order:i}).eq('id',list[j].id)]);load()};
  return <div><div className="flex gap-2 mb-6"><input className={`${input} flex-1`} value={name} onChange={e=>setName(e.target.value)} placeholder="New filter, e.g. Brand"/><button onClick={addFilter} className="bg-[#FFC21C] px-5 rounded-lg font-extrabold flex items-center gap-2"><Plus className="w-4 h-4"/> Create Filter</button></div><div className="space-y-4">{rows.map((f,i)=><section key={f.id} className="bg-white border rounded-2xl p-5"><div className="flex flex-wrap items-center gap-3"><input className={`${input} flex-1 min-w-40 font-bold`} defaultValue={f.name} onBlur={e=>updateFilter(f.id,{name:e.target.value,slug:slugify(e.target.value)})}/><label className="text-xs font-bold flex gap-2"><input type="checkbox" checked={f.is_active} onChange={e=>updateFilter(f.id,{is_active:e.target.checked})}/> Active</label><button onClick={()=>reorder(rows,i,-1,'product_filters')} aria-label="Move filter up"><ChevronUp className="w-4 h-4"/></button><button onClick={()=>reorder(rows,i,1,'product_filters')} aria-label="Move filter down"><ChevronDown className="w-4 h-4"/></button><button onClick={()=>removeFilter(f.id)} className="text-red-500" aria-label="Delete filter"><Trash2 className="w-4 h-4"/></button></div><div className="mt-4 space-y-2">{f.options.map((o:any,oi:number)=><div key={o.id} className="flex items-center gap-2 bg-neutral-50 rounded-lg p-2"><input className={`${input} flex-1`} defaultValue={o.label} onBlur={e=>updateOption(o.id,{label:e.target.value,value:slugify(e.target.value)||e.target.value.toLowerCase()})}/><label className="text-[11px] font-bold flex gap-1"><input type="checkbox" checked={o.is_active} onChange={e=>updateOption(o.id,{is_active:e.target.checked})}/> Active</label><button onClick={()=>reorder(f.options,oi,-1,'product_filter_options')}><ChevronUp className="w-3.5 h-3.5"/></button><button onClick={()=>reorder(f.options,oi,1,'product_filter_options')}><ChevronDown className="w-3.5 h-3.5"/></button><button onClick={()=>removeOption(o.id)} className="text-red-500"><Trash2 className="w-3.5 h-3.5"/></button></div>)}</div><div className="flex gap-2 mt-3"><input className={`${input} flex-1`} value={newOptions[f.id]||''} onChange={e=>setNewOptions(s=>({...s,[f.id]:e.target.value}))} placeholder={`Add ${f.name} option`}/><button onClick={()=>addOption(f)} className="border px-4 rounded-lg text-sm font-bold">Add Option</button></div></section>)}{!rows.length&&<p className="text-neutral-400">No filters yet. Create the first filter above.</p>}</div></div>;
}
